### ISSUE TITLE
Small Files shouldn't be deleted all the time

### ISSUE THREAD

**Issue by tblotko** [pdbme/pdbMate#9]
Is there a way to disable the small files deletion. I have some old AVI/WMV files in my collection which shouldn't be deleted.

**Comment by pdbme** [comment]
Currently there is no option to disable small files deletion. Simply store those files separately from your main working folder.

Maybe implementing a new option to exclude certain sub directories from being parsed by pdbMate could be a solution.

**Comment by tblotko** [comment]
ok, what is the minimum file size that files are considered as small files for pdbMate?

**Comment by pdbme** [comment]
It's 150 Mb and currently hard-coded.

**Comment by tblotko** [comment]
And files which aren't mp4 or mkv are also always removed, right?

**Comment by pdbme** [comment]
Yes. 

But let's take a step back and discuss your usage scenario. Can you explain how you are trying to use pdbMate?

Because renaming starts with a source folder and ends with a target folder. Both folders should be **different**. Only in the source folder, files are deleted. So you should put only files you want pdbMate to process in the source folder. The target folder on the other hand can contain existing collections (not renamed by pdbMate).

**Comment by tblotko** [comment]
I used it always with target and source the same folder. But yeah I will do it now the "correct" way.
